# Copyright (c) 2020 Eric Ernst
# SPDX-License-Identifier: Apache-2.0

FROM cr.loongnix.cn/library/golang:1.19-buster AS builder

RUN apt update && apt install -y curl git make
WORKDIR /go/src/github.com/kata-containers/kata-containers/src/runtime
COPY . /go/src/github.com/kata-containers/kata-containers
COPY tools/packaging/kata-monitor/yq  /go/bin/
RUN SKIP_GO_VERSION_CHECK=true make monitor

FROM cr.loongnix.cn/loongson/loongnix-server:8.4.0
COPY --from=builder /go/src/github.com/kata-containers/kata-containers/src/runtime/kata-monitor /usr/bin/kata-monitor
CMD ["-h"]
ENTRYPOINT ["/usr/bin/kata-monitor"]
